### ISSUE TITLE
Add a load_data() method

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/imexam#100]
Display an image using an existing np.array, instead of going through a file. May exist but my observational powers are limited.

**Comment by sosey** [comment]
The  view() method exists for looking at numpy or nddata arrays:

```
import imexam
import numpy as np
a=imexam.connect()  #start ds9 by default on X systems
data=np.random.rand(100,100)
a.view(data)
a.zoomtofit()

**Comment by stscieisenhamer** [comment]
See my observational powers failed. Thanks!

**Comment by stscieisenhamer** [comment]
So, I was looking for another 'load_***' method. Conversely, looking at the documentation for view, it has "view(img,...", and being mono-minded, I would have clued in on "view(array,...)" instead. "img" carries too many connotations, such as a FITS HDUL, or HDU, or jpeg/gif/png, etc. So, yes, probably a renaming/redocumenting, but definitely not based on this one datapoint.
