### ISSUE TITLE
Macports and imexam

### ISSUE THREAD

**Issue by iskreng** [spacetelescope/imexam#110]
Hi,

it seems that imexam is not available as a port on Macports. Is there any plan to port it?

Cheers,
Iskren

**Comment by sosey** [comment]
Hi  @iskreng  - I don't think there is a current plan to make it available on Macports, but I can look into it.  Is Macports the only thing you are using to manage your environment? Have you tried installing `imexam` with pip?

**Comment by iskreng** [comment]
Hi Megan,
I'm trying to stick to, and so far I've managed to get all I need via macports. But surely I can install imexam with pip (or downloading the source). I just wanted to keep my system more tidy.
If you find some time in the future, that'll be nice.
Cheers,
Iskren

**Comment by sosey** [comment]
I'm going to reopen this just so I don't forget it exists :) 
cheers
