### ISSUE TITLE
Fix extension references for MEF FITS image with image data in the PRIMARY extension

### ISSUE THREAD

**Issue by sosey** [spacetelescope/imexam#113]
This was also brought to light by #111.

Think about the best defaults to use and how to pass explicit user information so that the correct extension is always referenced regardless of how the user loads the data into `ds9`. Also verify that these changes don't break anything in the `ginga` interface.

**Comment by mcara** [comment]
@sosey I am not sure I understood everything but maybe something like [``stsci.skypac.utils.get_extver_list()``](https://github.com/spacetelescope/stsci.skypac/blob/master/stsci/skypac/utils.py#L299) may be of use... For example, to find all image-like extensions use:

```python
get_extver_list('file_name.fits', extname=None)
```

**Comment by sosey** [comment]
Thanks @mcara. I'm not sure I want to add another dependency, but the issue here isn't really getting the list of extensions, it's managing the extensions correctly between ds9's xpa and imexam.

**Comment by mcara** [comment]
> it's managing the extensions correctly between ds9's xpa and imexam

This is beyond my competencies 😃

**Comment by sosey** [comment]
certainly not - it's just in the weeds of how the two tools communicate :wink:
