### ISSUE TITLE
Adapt to photutils aperture photometry changes

### ISSUE THREAD

**Issue by cdeil** [spacetelescope/imexam#12]
Just a heads up: the current way `photutils` is called for aperture photometry by `imexam` (see [here](https://github.com/sosey/imexam/blob/ab9042684b8aea25036d7003b0110047105db87e/imexam/imexamine.py#L374) will break in the next days when https://github.com/astropy/photutils/pull/55 is merged.

There will be quite a few [API changes in photutils](https://github.com/astropy/photutils/issues?labels=API&page=1&state=open) coming in the next weeks ... it'll be easy to update `imexam` once that's finished.

**Comment by sosey** [comment]
fixed
