### ISSUE TITLE
Citable record?

### ISSUE THREAD

**Issue by adrn** [spacetelescope/imexam#120]
We're planning to reference and cite all Astropy affiliated packages in the upcoming Astropy v2.0 paper. I couldn't find a citable record for this package - are you interested in creating one so that we can cite it? For example, you can create a [zenodo](zenodo.org) record and just comment back here to let me know that it's done. Please also let me know if you'd like to opt out of a citation and we'll just link to the package. Thanks!

**Comment by sosey** [comment]
yah, I've been planning on doing this for ages and just haven't gotten around to it, will bump it to the top. Hoping to do a bugfix release later this week and will tag it there.  Is that soon enough?

**Comment by adrn** [comment]
Yep, that'll work - thanks!

**Comment by sosey** [comment]
sorry for the delay! The zenodo reference is published now with v0.8.0

**Comment by adrn** [comment]
thanks!
