### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by SaraOgaz** [spacetelescope/imexam#131]
Hi,

I'm passing on the following documentation request from @mackjenn:

The example for displaying an image shows how do do it in DS9 or Ginga
http://imexam.readthedocs.io/en/latest/imexam/examples.html#basic-usage

But the example for tvmark only shows how to load a coordinate list in Ginga.
http://ginga.readthedocs.io/en/latest/manual/plugins_local/tvmark.html

How do you do it in DS9??

**Comment by pllim** [comment]
@SaraOgaz , if your problem is with `TVMark` plugin, that belongs in Ginga's repo, not here. Also, documenting DS9 is out of scope for Ginga. IRAF's `tvmark` task is already documented at http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?tvmark (and that is the one people used with DS9).

**Comment by SaraOgaz** [comment]
Sorry, this was my bad.  @mackjenn, we can talk about this offline if you want.

**Comment by sosey** [comment]
There's is an example here: http://imexam.readthedocs.io/en/latest/imexam/examples.html#advanced-usage-interact-with-daophot-and-astropy

that shows how to mark objects in the DS9 image using imexam if you're still interested, mark_region_from_array() is the function. It's also shown in input line 23 here: https://github.com/spacetelescope/imexam/blob/master/example_notebooks/imexam_ds9_photometry.ipynb
