### ISSUE TITLE
Gitter for imexam

### ISSUE THREAD

**Issue by SimonKrughoff** [spacetelescope/imexam#139]
What is the suggested way for users to interact with the imexam dev team?  I have found gitter to be very useful, but I understand why teams would want to strictly use issues instead.

**Comment by pllim** [comment]
Hello. Thank you for your interest in `imexam`. Either GitHub issues here or sending a help call to `help[at]stsci.edu` is acceptable.

**Comment by SimonKrughoff** [comment]
Will do.

Have you thought about opening a gitter channel?  The real time aspect has really been a game changer for how I interact with open source projects.

**Comment by sosey** [comment]
I also keep up with the astropy slack channel, if you'd like to have a discussion there, there's a link to the astropy slack here: http://www.astropy.org/help.html. I created an affiliated-imexam channel we can try out there.

**Comment by sosey** [comment]
personally, I'm on gitter, but I tend to have more projects interacting on slack, so I find I use it more...

**Comment by SimonKrughoff** [comment]
OK, thanks.  I prefer gitter for open source projects because it seems more open, but I also definitely use slack more.  Slack has way more features.
