### ISSUE TITLE
imexam 'a' key doesn't plot phot annulus in DS9; 'c' and 'l' keys crash imexam session on Mac

### ISSUE THREAD

**Issue by lkeller** [spacetelescope/imexam#150]
Using Python 3.6.4, DS9 7.6 (XQuartz v2.7.11) on MacOS 10.13.5:

In imexam session pressing 'a' key prints photometry data to terminal, but does not 
plot the photometry annulus on the DS9 viewer. Also pressing 'c' or 'l' for plot
crashes imexam session with:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/imexam/connect.py", line 152, in imexam
    self._run_imexam()
  File "/usr/local/lib/python3.6/site-packages/imexam/connect.py", line 249, in _run_imexam
    x, y, current_key)
  File "/usr/local/lib/python3.6/site-packages/imexam/imexamine.py", line 181, in do_option
    self.imexam_option_funcs[key][0](x, y, self._data)
  File "/usr/local/lib/python3.6/site-packages/imexam/imexamine.py", line 311, in plot_line
    xmax = len(data[y, :])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Other plots (surface, contour, etc.) work just fine. Data are 2D FITS image with no NaNs,
but there are negative pixel values.

Check existing issues, but don't see anything similar.

Thanks

**Comment by sosey** [comment]
Thanks for the report! Can you give me some debugging information? What version of imexam are you running `imexam.__version__`, and what matplotlib backend are you using? `matplotlib.get_backend`

**Comment by lkeller** [comment]
imexam 0.8.0 and using TkAgg backend. Tried Qt5Agg and Qt4Agg but same behavior.
Thanks for looking into this.

**Comment by sosey** [comment]
I'm also running HighSierra, but I haven't been able to reproduce this issue, can you point me to a copy of your data so that I can investigate further?

**Comment by lkeller** [comment]
Here's a link to two FITS files I've tried to use with imexam. They are from different sources, but I get the same failure, reported above, with both of them.

https://www.dropbox.com/sh/5dgktt4b781h7rb/AADiA-kSN_6BD9kgzuqzhc9Ua?dl=0

**Comment by sosey** [comment]
@lkeller I still can't replicate, it's working for me in TkAgg and Qt4.  However, let's move you to the dev version and see if that fixes your bugs...I'm also releasing 0.8.1 today from this branch. You can either pull the repository yourself using git, or you can directly install using pip.  If you used conda to install imexam in your current environment remove it first:  `conda uninstall imexam --force` then you can pip install directly from the master branch here: `pip install git+https://github.com/spacetelescope/imexam`

**Comment by lkeller** [comment]
Uninstalling 0.8.0 and installing 0.8.1 fixed these problems! A new issue is that I get the spinning beach ball over any imexam plot windows. I can still use the imexam key functions, just can't interact with the current pyplot window (matplotlib-3.0.2). Here's the associated error:

invalid command name "4530443976idle_draw"
    while executing
"4530443976idle_draw"
    ("after" script)

This is progress, though. I can now use imexam so thanks for the help! Should I post the new issue separately?

**Comment by sosey** [comment]
excellent (for the first).  For the beach ball...are you using the TkAgg backend now or the Qt? I had no issue with QT4/5Agg with the plot windows closing. In TkAgg, the window would hang, but still update and allow functionality through imexam.  I think this might be a loop+threading issue when using imexam+matplotlib from an ipython terminal, as opposed to from an ipython console or a jupyter notebook.  You might try one of those combinations and see if you find the same to be true.  The draw issue seems like it's coming from matplotlib, which could be related. Before mucking with the backend, try starting your ipython  session with matploblib magics `%matplotlib` before importing imexam and see if that helps?

**Comment by lkeller** [comment]
Thanks. I'll give this a try.
