### ISSUE TITLE
Trouble starting starting new DS9 display before running imexamine

### ISSUE THREAD

**Issue by prdurrell** [spacetelescope/imexam#164]
I am having problems with starting up DS9 from within a jupyter notebook with the basic commands in the documentation (ticket INC0135973).  With

_viewer=imexam.connect( ) 
viewer.load_fits('jdkb12010_drc.chip1.fits')  
viewer.scale()_

I get the (dreaded?) error:    XpaException: Unknown XPA Error : XPAGet returned 0!

When I use the following:

_import os
os.environ['XPA_METHOD'] = "local"
viewer=imexam.connect( )  # startup a new DS9 window
viewer.load_fits('jdkb12010_drc.chip1.fits') 
viewer.scale()_  

I get a DS9 to open, then disappear!  See screenshot

![image](https://user-images.githubusercontent.com/48992231/55082610-61e1db00-5078-11e9-8d45-4cd08bd20184.png)

Finally, using an inet address 

_os.environ['XPA_METHOD'] = "inet:5137"_

will create the DS9 window, but not display the image.

 I am interested in using imexamine interactively, so simply starting a new DS9 before running imexamine would help!   Not sure if other sockets will work
.
**_NOTE: I can get imexamine to work if I have DS9 pre-loaded, get the inet socket, and then input that into the code each time I run this.   I was hoping that the  imexam.connect() could work without adding in wait times_**

Mac OX El Capitan, DS9 v7.6, imexamv0.8.2, python3.7

**Comment by sosey** [comment]
ah - Jupyter notebook, got it. Just quickly -  you should only set `XPA_METHOD` to `inet`, not 5137, that's an iraf port thing... Will you give it a go with the lated DS9, v8.0.1?

**Comment by sosey** [comment]
Also, is your mode of normal interaction that you open then notebook, and then `run all` the cells with the intention of getting to something else, or are you running through by hand for interactive analysis? If you run all, there's no wait for the connection to finalize and you should add a sleep(2) like in the related ticket (#162). Interactively, wait for the DS9 window to appear and you should be okay. 

For my information collection, what is your use-case for imexam? If I know how people are using it I can try and make these type of things more automated and suited to broader use cases., I may be able to go in an put a hook to catch that the connection isn't fully ready and force imexam to wait.

**Comment by prdurrell** [comment]
Hi -- just using "inet" does not help, I have found.    I was using DS9 v7.6 as that is the latest version conda update would give.   I will try v8.0.1
  I am running through by hand for interactive analysis, but the imexam.connect() and the loading of the image are in the same cell, and run together.

**Comment by sosey** [comment]
it's a DS9 startup timing thing...lemme see what I can do behind the scenes to get the socket connection better timed, if you are just interactive, put the commands in separate cells for now and wait for ds9() to startup before loading the image, that should at least get you going....let me know if you still can't connect properly though...

**Comment by prdurrell** [comment]
I suppose I am still trying to run 'imexamine' much as I would with IRAF/PYRAF -- simply display an image, and run the interactive mode and have displays/output to another window.   I do not normally run things in any type of batch mode, or give lists of co-ordinates in a table.

**Comment by prdurrell** [comment]
FInally...not sure how to update conda with DS9 V8.0.1, as conda has 7.6 built-in.    Is there a way to update ds9 in conda to a linked executable (eg. Mac executable from SAO) with a newer version?

**Comment by prdurrell** [comment]
I am putting the commands in separate cells for now, and that seems to work.  Many thanks!

**Comment by pllim** [comment]
> not sure how to update conda with DS9 V8.0.1

Theoretically, this would work: Uninstall DS9 completely from `conda`. Install the standalone version and make sure it is installed somewhere in your PATH. *NIX path resolution would take care of the rest.

**Comment by sosey** [comment]
one more - I see the `wait_time` message,  are you loading the notebook across an internet connection, ie from a non-local computer or server? `local` shouldn't result in the connection killing ds9 unless there's something else going on. You might try using `local` and extending the wait time by adding a few seconds, i.e. `a=imexam.connect(wait_time=15)`. 

update ds9 - you can download the latest ds9 from the website and install, though this will be outside conda, but shouldn't keep you from also installing and using a particular version in your conda environments. We have the latest version available on a dev channel, but I dont want to publicize that. I'll talk to the locals about updating the version we serve in our astroconda channel.

**Comment by prdurrell** [comment]
Thanks for the info.    I will also try the wait_time...have not yet experimented with that.   Once I get V8.0.1 working, I will test that also to see if it makes any difference.

**Comment by sosey** [comment]
cool. Thanks for reporting your issues, I really appreciate the feedback :)

**Comment by prdurrell** [comment]
OK...updated astroconda environment to include DS9 v8.0.1 using Anaconda Navigator.   That seems to have worked OK, but I still saw the same problem with 7.6 --XpaException: Unknown XPA Error : XPAGet returned 0!  when I ran  (in one cell).  Looks to be the same issue.

_viewer=imexam.connect()  
viewer.load_fits('jdkb12010_drc.chip1.fits')  
viewer.scale()_  

I can still work with running things in individual cells.   I may have more questions about imexam, but in a different thread...

**Comment by sosey** [comment]
no problem. yah, the load timing issue should be regardless of version...sure, I'll look for new issues.. :)
