### ISSUE TITLE
XpaException raised because it expects an integer and finds a float

### ISSUE THREAD

**Issue by b1quint** [spacetelescope/imexam#186]
Dear all,

I am running `imexam` on a MacOS 10.14.5 using the following setup:
- `conda 4.7.10`
- `python 3.6.8`
- `ds9 8.0.1`
- `imexam 0.8.1`

I run the following code and everything seems fine:
```
import imexam
v = imexam.connect()                                                                                                                                  
v.load_fits("Notebooks/data/simple_image.fits")                                                                                                       
v.imexam()
```
When pressing a key on DS9 to start analysing the image (e.g. `a` or `r`), I get an error. The traceback is attached. 
[imexam_traceback.txt](https://github.com/spacetelescope/imexam/files/3482751/imexam_traceback.txt)

The traceback tells that XPA is expecting the cursor position as an integer value but is receiving a float. Based on some discussions on Slack, it seems that there is an incompatibility between DS9 and `imexam` versions (or XPA version?). 

I installed DS9 v7.4 and everything works fine.

**Comment by b1quint** [comment]
Update: After fiddling around with different DS9 versions, I cannot reproduce the error on my machine anymore. That makes me wonder if the real source of the issue is the version of XPA.

**Comment by sosey** [comment]
Apologies - I've been swamped and will try and get to this soon

**Comment by b1quint** [comment]
Do not worry. Let me know if you need any help on testing anything or trying to get more information for debugging.

**Comment by sosey** [comment]
@b1quint have you tried this recently? I'm not seeing an issue with the following:
* ds9  8.0.1
* python 3.7.2
* conda 4.7.12

**Comment by b1quint** [comment]
Not yet! I will give a try and report!

**Comment by b1quint** [comment]
@sosey I am sorry for the delay! I tried this and it is now working fine! Thank you very much!

**Comment by sosey** [comment]
excellent! I've been crazy busy myself, thanks for reporting back :)
