### ISSUE TITLE
photutils.aperture 0.7 API incompatible with imexam 

### ISSUE THREAD

**Issue by hjmcc** [spacetelescope/imexam#194]
This change in photutils.aperture breaks some functionality in imexam plotting. 
https://github.com/astropy/photutils/pull/854

**Comment by sosey** [comment]
try the code from this PR: https://github.com/spacetelescope/imexam/pull/195 and let me know if it's working for you. I tried it with 0.6.dev28+g5fc8f449   and 0.7.1
