### ISSUE TITLE
Matplotlibe deprecation warning

### ISSUE THREAD

**Issue by jchavez1992** [spacetelescope/imexam#214]
I am fairly new to using python/imexam.  I was a little surprised on the first time I imported it, I got this deprecation warning from Matplotlib: [path]/miniconda3/envs/dragons/lib/python3.6/site-packages/ginga/cmap.py:13317: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API

Maybe ginga is not within the scope of imexam, but I thought it was worth reporting. 

If it helps, I found this when I did a google search of the Deprecation Warning: https://github.com/holoviz/holoviews/issues/4531

**Comment by sosey** [comment]
Ah, yes, ginga development isn't in scope with imexam, but I'll double check the version we are using and what @ejeschke and @pllim are working on for the deprecation...

Are you using imexam with ginga or ds9?

**Comment by pllim** [comment]
Re: Ginga -- Are you using a very old version of Ginga? I don't see that warning on `master`. And also we just dropped support for Python 3 on `master`. If you can give a code snippet to reproduce on Ginga, please open issue at https://github.com/ejeschke/ginga/issues

**Comment by ejeschke** [comment]
I can see where this is coming from.  Looks like a few other projects are bitten by the [same deprecation](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cm.py#L75-L118).

I filed [an issue](https://github.com/ejeschke/ginga/issues/890) in Ginga github.
