### ISSUE TITLE
 install aborted in 0.9.1

### ISSUE THREAD

**Issue by baja2k9** [spacetelescope/imexam#227]
hello,

There is a typo? in release 0.9.1, coud not install:
Collecting imexam
  Downloading https://files.pythonhosted.org/packages/c5/1f/4b735cf7d2558c9356a884bcaca02c098bd3bd499f8727787affbf177ee0/imexam-0.9.1.tar.gz (21.4MB)
    100% |████████████████████████████████| 21.4MB 66kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-PAQtxS/imexam/setup.py", line 218
        print(f"removing {myfile}")
                                 ^
    SyntaxError: invalid syntax

**Comment by sosey** [comment]
it's an f-string, and works in python 3.6+, check your installed version of python? and then check your environment to make sure it's pulling the version of python you expect?

**Comment by baja2k9** [comment]
I was trying to update my old server (Ubuntu 18.04.5 LTS) script that uses Python 2.7.17.

Will leave with 0.8.1.  as new version did not install.
Thanks,

**Comment by sosey** [comment]
ahhh, that would be it!  Yah, the newer versions of the package are no longer py2.7 compliant.
I'll close this, let me know if you have any other issues.
