### ISSUE TITLE
imexam 'Circle' object has no property 'ax'

### ISSUE THREAD

**Issue by jazamatazz** [spacetelescope/imexam#228]
I am trying to find the center of stars using imexam circular apterture photometry
I am using a jupyter notebook.
I have ds9 version 8.1 and imexam version 0.9.1, python version 3.8.8 and am on Ubuntu 20.04.2 LTS x64.

When I launch imexam and press a on my star, I get an attribute error stating that the 'Circle' object has no property 'ax'. I am not sure how to troubleshoot this and any help is appreciated.
Thank you!
![image](https://user-images.githubusercontent.com/68238960/122502497-bf99cf00-cfc4-11eb-9a40-a2218ffba159.png)

**Comment by marcusthomas11** [comment]
Hi there,

The photutils package removed the 'ax' keyword in version 1.0.0, along with a number of other changes that broke a few other packages. 

I downgraded to the last, version 0.7.2.

I had the same issue, but it seems to all work now. Until the calls are changed in this package, you'll need to downgrade photutils.

**Comment by jazamatazz** [comment]
That worked! Thank you so much!
