### ISSUE TITLE
Ds9 display closing seconds after opening

### ISSUE THREAD

**Issue by asymone** [spacetelescope/imexam#31]
I am trying to execute this code in a script:
```python
#Create region file
    master_list = []
    if man_sources:
        for ogc in man_sources:
            master_list.append('circle {} {} 10 #color=red'.format(ogc[0],ogc[1]))
    if casjobs_sources:
        for ogc in casjobs_sources:
            master_list.append('circle {}d {}d 12 #color=green'.format(ogc[0],ogc[1]))
    #DS9
    viewer=imexam.connect()
    viewer.load_fits(fits_image)
    viewer.scale()
    for reg in master_list:
        viewer.set_region(reg)
```

When I run the script it opens ds9 and then displays the circles for a millisecond and then quits.  I have grabbed this newer version of imexam and the problem still persist.

I am using the 7.1 version of ds9.

**Comment by sosey** [comment]
I haven't had a chance to try and replicate this - but have you tried starting ds9 yourself and connecting to the window?

viewer=imexam.connect("name_of_ds9_window")  #which defaults to ds9, or you can name it when you startup ds9. You can also give it the XPA name referenced in the menu

**Comment by sosey** [comment]
haven't been able to replicate, @asymone do you still have this issue?

**Comment by sosey** [comment]
I think this has been fixed
