### ISSUE TITLE
Python 3 compatiliblity

### ISSUE THREAD

**Issue by mwcraig** [spacetelescope/imexam#37]
I noticed at least one spot where the code isn't python 3 compatiable, an import of StringIO in [imexamine.py](https://github.com/spacetelescope/imexam/blob/master/imexam/imexamine.py#L21). I didn't do a comprehensive check for other python 3 issues, so there may be others.

**Comment by sosey** [comment]
Thanks. I'll try and do a better check of python 3 compatibility for my next checkin.

**Comment by pllim** [comment]
I think if you do `from __future__ import unicode_literal`, it will catch some of the string stuff.

**Comment by tepickering** [comment]
the `StringIO` import issue is fixed by instead doing:
```
from io import StringIO
```
this will work for both python2 and python3.

**Comment by sosey** [comment]
I haven't had time to work on imexam since June, Tim if you're using/fixing things feel free to update or send a pull request

**Comment by tepickering** [comment]
ok, will see if i can make a PR for this.

**Comment by sosey** [comment]
StringIO updated in a5b7946131729ed1395838f2db8f0e82d5668695, haven't run into others yet on python 3.5.1

**Comment by sosey** [comment]
should be fixed on the master
