### ISSUE TITLE
Matplotlib window doesn't update until "q"

### ISSUE THREAD

**Issue by eteq** [spacetelescope/imexam#43]
I was just trying imexam right now with the latest conda (using the most recent matplotlib, astropy, and photutils), and, at least on my machine (OS X Yosemite), when I try any of the imexam plots, the matplotlib window pops up but does not render any plot - the cursor over the window yields only the "spinning beachball".  I tried both the ds9 and ginga backends - in ginga's case it meant the image didn't appear *at all*, whereas for ds9 the ds9 behavior worked fine but none of the plots showed up.

My guess is this is due to some sort of threading behavior oddity, but I'm not well versed enough in how imexam talks back and forth with matplotlib to do more than guess...

**Comment by sosey** [comment]
yah, already fixed that, is change in blocking for matplotlib. I was trying to fix some travis tests and this on the same branch, and then also added radial intensity plots, I'll check in the updates soon - trying to fix one last bug with the new radial plots. I'll send you a note when I push the update to the travisfix branch

**Comment by pllim** [comment]
@sosey , is your fix only for `matplotlib`, or also for Ginga and DS9?

**Comment by sosey** [comment]
nothing to do with ginga

**Comment by sosey** [comment]
you can try pulling the travisfix branch and see if that fixes the issue for you...

**Comment by eteq** [comment]
@sosey - Ah, yep, that did it.  It still doesn't want to let my interact in the matplotlib window (zoom boxes and such), but the plot does show up now.

The ginga thing is still happening.  I'm guessing that's on ginga's end, though, now that I think about it - perhaps the same blocking changes that led to this happening in imexam...?

**Comment by pllim** [comment]
Just for the records, I am unable to reproduce the Ginga problem under RHEL6 Anaconda Python 2.7.11 with the latest dev version of Ginga. I can open the viewer and display an image using:

```python
import imexam
viewer = imexam.connect(viewer='ginga_mp')
viewer.load_fits('image.fits')
```

**Comment by eteq** [comment]
Ah, the latest matplotlib is 1.5.1, and I think 1.5 is when the changes to the interactive stuff was done (http://matplotlib.org/1.5.1/users/whats_new.html#interactive-oo-usage), which I suspect is the root cause of all of this.

**Comment by sosey** [comment]
yes, exactly
