### ISSUE TITLE
setattr works differently in python3

### ISSUE THREAD

**Issue by sosey** [spacetelescope/imexam#47]
arg

**Comment by embray** [comment]
Just out of curiosity what did you run into that `setattr` works differently?  The only thing I can think of is that the attribute name must be a `str` instead of `bytes` object but I'm curious what else there could be.

**Comment by sosey** [comment]
yah, cryptic message to myself because I didn't have time to investigate further during the workshop last week.  Anyways, I'm using setattr as part of a call to attach a user created function to an object that's already in existence , it happens here:

@classmethod
    def _add_user_function(cls, func):
        import types
        return setattr(cls, func.__name__, types.MethodType(func, None, cls))

I think it works in python 2 because unbound methods are allowed....but not in python 3. 
I've been home sick the last couple days, maybe I'll mess around with it today and see if I can come up with something better, and be less tricky for my own good.

**Comment by sosey** [comment]
fixed in merge with ginganb branch

**Comment by pllim** [comment]
So, what was the solution? Your initial "arg" got me curious.

**Comment by pllim** [comment]
Ooooo thx

**Comment by embray** [comment]
Oh yeah, this isn't a difference in how `setattr` works at all but you figured that out.
