### ISSUE TITLE
m key raises AttributeError

### ISSUE THREAD

**Issue by justincely** [spacetelescope/imexam#61]
After a quick connection, pressing "m" hits an attribute error: last of the traceback is below.

/Users/ely/anaconda3/envs/astroconda3/lib/python3.5/site-packages/imexam/imexamine.py in report_stat(self, x, y, data)
    310             ymax = int(y + dist)
    311             pstr = "[{0:d}:{1:d},{2:d}:{3:d}] {4:s}: {5:f}".format(
--> 312                 xmin, xmax, ymin, ymax, stat.func_name, (stat(data[ymin:ymax, xmin:xmax])))
    313             print(pstr)
    314             logging.info(pstr)

AttributeError: 'function' object has no attribute 'func_name'

**Comment by sosey** [comment]
Can you give me more information on the version you are using and how you are using it? I don't see this problem on master:

Current image /Users/sosey/test_images/iacs01t4q_flt.fits
pressed: m, report_stat
[321:326,429:434] median: 0.662824
pressed: m, report_stat
[321:326,429:434] median: 0.662824
pressed: m, report_stat
[321:326,429:434] median: 0.662824
pressed: m, report_stat
[321:326,429:434] median: 0.662824
pressed: m, report_stat
[321:326,429:434] median: 0.662824

**Comment by justincely** [comment]
You're right - i was using the pip version.  Installed from master and everything is fine.

**Comment by sosey** [comment]
great. Hopefully by the end of the week I'll manage to get this version update out and pushed.
