### ISSUE TITLE
Small request for list_active_ds9()

### ISSUE THREAD

**Issue by emcangi** [spacetelescope/imexam#71]
Hello! I'm relatively new to using pyraf and imexam (and Github, to tell the truth), so please excuse me if this has been asked before or I'm going about any of this incorrectly. I have checked the previous issues and did not see it.

I noticed that list_active_ds9() prints the current DS9 session to the terminal. I wanted to be able to collect the XPA_METHOD via my script instead of manually finding it in my DS9 window, so I dug into my libraries and changed this code:

    if find_xpans():
        try:
            ...
            if ..(stuff)
            else:
                print(sessions.decode())

To this:

    if find_xpans():
        try:
            ...
            if ..(stuff)
            else:
                return sessions.decode()

This allows me to collect the string that list_active_ds9() spits out and parse it to grab the XPA_METHOD. This works for my purposes, though I realize it may cause issues if users have multiple DS9 windows open. Would you consider adding perhaps a toggle-able option to either return the values or print the values, depending on user needs? If you like the idea, I can contribute the code change if that is allowed on this repository.

Thanks for this very helpful module!

**Comment by pllim** [comment]
Is this what #60 was trying to address?

**Comment by emcangi** [comment]
Yes, thanks! I'll close this.

**Comment by pllim** [comment]
Let's keep this open until the PR is merged.

**Comment by sosey** [comment]
Hi @emcangi , indeed you are the second person to ask for this, I'm going to make some suggestions on the original PR and copy you there.

**Comment by sosey** [comment]
fixed in 2f42089ba689e85c6ef02b8ce92a75e7344ae198
