### ISSUE TITLE
Calling setlog successively with different filenames does not actually open new files

### ISSUE THREAD

**Issue by emcangi** [spacetelescope/imexam#74]
Hello again! I have written a script that auto-opens FIT files from various subdirectories in a directory and cycles through them and starts imexam for me, allowing me to use tasks. I have set the script to log anything I do to a log file. I would like to have different log files for every image, but even though I update the log file name for each new image, it doesn't actually save to that new file (even though it prints a message saying it does).

My code:

```
XPA_METHOD = whatever_it_is

v = imexam.connect(XPA_METHOD)

imgdirlists = [ ['path/to/folder', ['img1.FIT', 'img2.FIT]], 
                          ['path/to/folder2', ['img3.FIT', 'img4.FIT']] ] # etc

for sublist in imgdirlists:
    imgnames = sublist[1]
    curdir = sublist[0]
    if sublist[1]:    # makes sure the directory isn't empty, e.g. a top-level
        for image in imgnames:
            path = "{}/{}".format(curdir, image)
            v.load_fits(path)
            # set the log file name. use of [:-4] just omits the .FIT extension.
            v.setlog(filename="{}_sky".format(image[:-4]), on=True)
            v.imexam()
            # I tried the following to see if it helped, but it did not.
            v.setlog(filename="{}_sky".format(image[:-4]), on=False)
    else:
        pass
```

This puts out a file with the name of the first image I started on, filled with data like this:

> _run_imexam 
> Current image /path/to/the/photo/14-57-57-755.FIT
> 
> (task results 1)
> (task results 2)
> ...
> 
> _run_imexam 
> Current image /path/to/the/photo/14-57-41-217.FIT
> 
> (task results 1)
> (task results 2)
> ...
> 
> <more photos>

The goal of course is to have each of those image lines and their results be in separate files. I tried looking at the util.py and connect.py code to see if I could fix it myself, but I'm afraid I don't know much about logging, and it wasn't clear to me where the issue was. It seems to be maybe related to the caveat in the docstring for set_logging:

> Notes
>     -----
>     basicConfig defaults to opening the file in append mode
>     There's still an issue here that if the user deletes the
>     log file and then continues on with functions which log
>     information, no new file is opened again and nothing gets written

Has this been noticed by others, or are there any suggestions as to fixing it?

thank you!

**Comment by sosey** [comment]
@emcangi you're still on my radar, just swamped at the moment.  I haven't spent a ton of time messing with the logging in this package, but I have a couple ideas and will get back with you as soon as I can.

**Comment by emcangi** [comment]
It's no rush at all. I'm studying for the physics GRE anyway, so my project is going slowly as it is. :)

**Comment by sosey** [comment]
@emcangi  the logging should be fixed on the current master, will do an official release tomorrow. Check it out when you have time and let me know if it's working for you.

**Comment by emcangi** [comment]
Thanks! I am just getting around to this. I updated today but I am now getting an error where I'm no longer able to load my files into DS9 anymore. Has something changed in load_fits? The error looks pretty buried:
```
Using directory /home/mypathname, image 14-41-57-630.FIT
/home/mypathname/14-41-57-630.FIT None 1
Traceback (most recent call last):
  File "collect_skystats.py", line 119, in <module>
    v.load_fits(path)
  File "/home/myusername/anaconda3/envs/astroconda/lib/python2.7/site-packages/imexam/connect.py", line 373, in load_fits
    self.window.load_fits(*args, **kwargs)
  File "/home/myusername/anaconda3/envs/astroconda/lib/python2.7/site-packages/imexam/ds9_viewer.py", line 1177, in load_fits
    self.set(cstring)
  File "/home/myusername/anaconda3/envs/astroconda/lib/python2.7/site-packages/imexam/ds9_viewer.py", line 666, in set
    self.xpa.set(param, buf)
  File "/home/myusername/anaconda3/envs/astroconda/lib/python2.7/site-packages/imexam/xpa_wrap.py", line 19, in set
    super(XPA, self).set(param.encode('utf-8', 'strict'), buf)
  File "wrappers/xpa.pyx", line 176, in xpa.xpa.set (wrappers/xpa.c:2487)
  File "wrappers/xpa.pyx", line 146, in xpa._set (wrappers/xpa.c:1920)
xpa.XpaException: XPA$ERROR Unable to load fits  /home/mypathname/14-41-57-630.FIT[1] (DS9:ds9 7f000101:32848)
```

In particular the line "/home/mypathname/14-41-57-630.FIT None 1" looks like it's being generated from some code that isn't mine. I'm not sure what it indicates.

I can't test the updated logging function until I get past this, unfortunately!

**Comment by pllim** [comment]
Re: attaching file. Theoretically, according to [this GitHub doc](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/), you can zip the FITS first, before attempting to attach, as long as it does not exceed size limit.

**Comment by sosey** [comment]
@emcangi I'm guessing it's your fits file, you could stick it on Box somewhere too, I haven't been able to replicate this with any of my fits files.  Have you tried opening the file directly with DS9 first? Also, what version of DS9 are you using?

**Comment by emcangi** [comment]
yup--and the files opened just fine in version 0.5.2, so I reverted to that version to continue working for now. 

DS9 version is apparently 7.4 and is part of the stsci package in astroconda (everything I have is installed and managed in an astroconda/anaconda environment). are you using version 7.5? I see it's available on the website but doesn't seem to be available to astroconda.

I'm attaching an example of one of my FIT files here. They're generated by some camera software associated with [this camera](http://www.telescope.com/Astrophotography/Astrophotography-Cameras/Orion-StarShoot-All-In-One-Astrophotography-Camera/c/4/sc/58/p/103030.uts), and I haven't been super impressed by the documentation/software capabilities for various Orion cameras, so.... eh. Wouldn't be surprised if the FIT format is wrong.

[problemFITfile.zip](https://github.com/spacetelescope/imexam/files/712317/problemFITfile.zip)

**Comment by sosey** [comment]
huh, 0.6.2 (conda update imexam=0.6.2) seems to work, def upgrade to that and give it a go at least loading this file. I see the fail on 0.6.3, but don't see the change affecting the image loading, lemme look around a bit...

**Comment by sosey** [comment]
Update to v0.6.3 and try this:  ```a.load_fits('21-5-57-172.FIT',extver=0)```, your image is a simple fits image with no extensions and the data and global together, I updated code around detecting simple fits. Let me see if I can make it smarter..

**Comment by emcangi** [comment]
It does indeed open successfully now, though I now have a different error:

```
Saving imexam commands to '14-41-57-630_sky'

Press 'q' to quit

2	Make the next plot in a new window
a	Aperture sum, with radius region_size 
b	Return the 2D gauss fit center of the object
c	Return column plot
e	Return a contour plot in a region around the cursor
g	Return curve of growth plot
h	Return a histogram in the region around the cursor
i	Modified stat display function, displays all the same stats that are normally displayed in imexamine's 'm' task
j	1D [Gaussian1D default] line fit 
k	1D [Gaussian1D default] column fit
l	Return line plot
m	Square region stats, in [region_size],default is median
r	Return the radial profile plot
s	Save current figure to disk as [plot_name]
t	Make a fits image cutout using pointer location
w	Display a surface plot around the cursor location
x	Return x,y,value of pixel
y	Return x,y,value of pixel
Current image /home/emc/GoogleDrive/Phys/Research/BothunLab/SkyPhotos/NewCamera/3January2017/3Jan-2/11/400microsec/14-41-57-630.FIT
Traceback (most recent call last):
  File "collect_skystats.py", line 114, in <module>
    v.imexam()
  File "/home/emc/anaconda3/envs/astroconda/lib/python2.7/site-packages/imexam/connect.py", line 141, in imexam
    self._run_imexam()
  File "/home/emc/anaconda3/envs/astroconda/lib/python2.7/site-packages/imexam/connect.py", line 213, in _run_imexam
    self.exam.set_data(self.window.get_data())
  File "/home/emc/anaconda3/envs/astroconda/lib/python2.7/site-packages/imexam/ds9_viewer.py", line 1044, in get_data
    data = filedata[extname, extver].data
  File "/home/emc/anaconda3/envs/astroconda/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 196, in __getitem__
    idx = self.index_of(key)
  File "/home/emc/anaconda3/envs/astroconda/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 519, in index_of
    raise KeyError(key)
KeyError: (None, 1)

```

This was for a different image--I tried the one I sent you but apparently I have some other issue with my code where it fails to open the file when I am selecting them manually (normally it loops through a directory with a bunch of nested directories). This might take me a bit to hammer out.

**Comment by emcangi** [comment]
Checked with the image I sent--same error as above:

```
Current image /home/mypath/21-5-57-172.FIT
Traceback (most recent call last):
  File "collect_skystats.py", line 95, in <module>
    v.imexam()
  File "/home/myusername/anaconda3/envs/astroconda/lib/python2.7/site-packages/imexam/connect.py", line 141, in imexam
    self._run_imexam()
  File "/home/myusername/anaconda3/envs/astroconda/lib/python2.7/site-packages/imexam/connect.py", line 213, in _run_imexam
    self.exam.set_data(self.window.get_data())
  File "/home/myusername/anaconda3/envs/astroconda/lib/python2.7/site-packages/imexam/ds9_viewer.py", line 1044, in get_data
    data = filedata[extname, extver].data
  File "/home/myusername/anaconda3/envs/astroconda/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 196, in __getitem__
    idx = self.index_of(key)
  File "/home/myusername/anaconda3/envs/astroconda/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 519, in index_of
    raise KeyError(key)
KeyError: (None, 1)
```

This looks like it's still having trouble reading the FIT file, although I have had success using the hdulist stuff myself to throw together simple plots. Hmm...

**Comment by sosey** [comment]
Some more background; the FITS file in question is a lying liar that lies ;) In truth, it's not actually violating the FITS standard to set EXTEND = True and then not have extensions, but it's not friendly.

```
In [4]: fits.info('21-5-57-172.FIT')
Filename: 21-5-57-172.FIT
No.    Name         Type      Cards   Dimensions   Format
  0  PRIMARY     PrimaryHDU      10   (640, 480)   uint8   

In [5]: fits.getval('21-5-57-172.FIT',ext=0,keyword='EXTEND')
Out[5]: True

```
If there are other issues with your FIT file not be standard that could be problematic too...oh, I see your updated comment.  For the error above ... edit your FIT image to set NEXTEND = F and see if the astropy.io.fits is happier...

**Comment by emcangi** [comment]
Apologies, I'm not quite sure what you mean by EXTEND/NEXTEND and how I might edit those. I am but a lowly student and still fairly new to FITS :). Is it EXTEND or NEXTEND? Is there a standard for editing FITS? It doesn't display properly in my text editor.

I'll have to come back to this after class. Thanks again for your help with this, I really appreciate it.

**Comment by sosey** [comment]
No worries... here's an example using astropy.io.fits
```
from astropy.io import fits
image=fits.open('21-5-57-172.FIT', mode='update')
image[0].header['EXTEND']=False
image.close()

# double check
fits.getval('21-5-57-172.FIT','EXTEND')
```
Now the image has the EXTEND keyword set as False.
NEXTEND is the keyword which tells fits readers how many extensions they might expect from a multi-extension fits files. Fits files with only data attached to the primary header are referred to as simple fits files. Here's an example of a multi-extension fits file:
```
In [9]: image=fits.open('iacs01t4q_flt.fits')

In [10]: image.info()
Filename: iacs01t4q_flt.fits
No.    Name         Type      Cards   Dimensions   Format
  0  PRIMARY     PrimaryHDU     235   ()      
  1  SCI         ImageHDU        81   (1014, 1014)   float32   
  2  ERR         ImageHDU        43   (1014, 1014)   float32   
  3  DQ          ImageHDU        35   (1014, 1014)   int16   
  4  SAMP        ImageHDU        29   (1014, 1014)   int16   
  5  TIME        ImageHDU        29   (1014, 1014)   float32   

In [11]: image[0].header['EXTEND']
Out[11]: True

In [12]: image[0].header['NEXTEND']
Out[12]: 5
```
Where if I wanted to get the data array which is from the 5th extension:
```
image[5].data  # reference it directly
data5 = image[5].data  # copy to a different variable

** watch out because this links back to the original data array so changes 
you make to data5 happen to image[5].data

In [16]: data5[0]
Out[16]: 
array([ 227.93692017,  227.93692017,  227.93692017, ...,  227.93692017,
        227.93692017,  227.93692017], dtype=float32)

In [17]: data5[0,0]
Out[17]: 227.93692

In [18]: data5[0,0] = 100

In [19]: image[5].data[0,0]
Out[19]: 100.0

```

**Comment by emcangi** [comment]
Thanks! I guess I realized I haven't gone through the FITS documentation very thoroughly. 

It now works that I set EXTEND to F. There is no NEXTEND in my files. 

I guess now I have to write another script to manage the FITS files...! T_T

**Comment by sosey** [comment]
@emcangi I'm not sure what else your script is doing, but my next update should fix the errors you had with loading this fits file (as is, without changing the EXTEND keyword or specifying the zero extension) and with the get and set data functions. Check back this afternoon and you should see the update, and not have to do anything to your fits images themselves.

**Comment by emcangi** [comment]
My apologies for the delay on this again. I tested version 0.7 and I am now getting a different error and DS9 is unable to connect:

```
Traceback (most recent call last):
  File "collect_skystats.py", line 19, in <module>
    ds9data = imexam.list_active_ds9()
  File "/home/my_site-packages_path/imexam/util.py", line 85, in list_active_ds9
    except xpa.XpaException:
NameError: global name 'xpa' is not defined
```

Sounds like maybe some variable was changed somewhere?

**Comment by sosey** [comment]
ugh! This was totally my fault when I was adding logic for windows users.  Pushing an update in the next few minutes....

**Comment by emcangi** [comment]
Everything is working perfectly now!

I hit a minor bump when I noticed that logging stopped working entirely with my user-defined imexam task (I call it 'i': it reports all the possible stats one can get out of the 'm' task). I discovered the cause was that when I defined the task, I imported `logging` and then called `logging.info(mymsg)`. After digging into imexamine.py, I discovered the correct way to do it to work with the imexam module was to call `self.log.info(mymsg)` instead.

I'm not sure where I originally got the idea to call `logging.info(mymsg)`. I'm also not sure if maybe this was the reason all commands were only going to one file. If it is... I'm sorry to have sent you down a wild goose chase! But I suppose some other improvements to the code occurred, so at least there's that. :)

Just in case you are interested, here is my function which reports all the stats that 'm' reports, but simultaneously.

```
def all_m_stats(self, x, y, data=None):
    """
    reports all the statistics available with the 'm' task simultaneously, 
    operating on a box with side region_size.
    The statistics are mean, std, median, min, max.
    
    :param x: the x location of the object
    :param y: the y location of the object
    :param data: numpy array, the data array to work on
    """
    import numpy as np 

    if data is None:
        data = self._data

    region_size = self.report_stat_pars["region_size"][0]

    dist = region_size / 2
    xmin = int(x - dist)
    xmax = int(x + dist)
    ymin = int(y - dist)
    ymax = int(y + dist)

    stat = getattr(np, 'mean')
    stat2 = getattr(np, 'std')
    stat3 = getattr(np, 'median')
    stat4 = getattr(np, 'min')
    stat5 = getattr(np, 'max')

    cols = "SLICE   NPIX   MEAN   STD   MEDIAN   MIN   MAX\n"
    box = "[{}:{},{}:{}]  ".format(xmin, xmax, ymin, ymax)
    area = "{}  ".format(region_size)
    sr1 = " {}  ".format(stat(data[ymin:ymax, xmin:xmax]))
    sr2 = "{}  ".format(stat2(data[ymin:ymax, xmin:xmax]))
    sr3 = "{}  ".format(stat3(data[ymin:ymax, xmin:xmax]))
    sr4 = "{}  ".format(stat4(data[ymin:ymax, xmin:xmax]))
    sr5 = "{}".format(stat5(data[ymin:ymax, xmin:xmax]))
    pstr = cols + box + area + sr1 + sr2 + sr3 + sr4 + sr5

    print(pstr)
    self.log.info(pstr)
```

thanks again!

**Comment by sosey** [comment]
@emcangi You can also set the 'm' key  stat to use the scipy.stats.descibe function, which returns all the stats at once :)    Use ```set_plot_pars("m","stat","describe")```

Now the output should look like this:
```
pressed: m, report_stat
[551:556,653:658] describe:
nobs: 25
minmax: (0.51326549, 0.85604763)
mean 0.6851165890693665
variance: 0.00780616095289588
skew: 0.05719175934791565
kurtosis: -0.47930471400886976
```
additionally, if you also want median you can ```set_plot_pars("m","stat","median")``` and call on the same location again.  But as you've done above, you can write your own function and attached it to an unused key in the imexam loop as well :)

**Comment by sosey** [comment]
also, thanks for being such a great tester :)   Yes, I changed the way the logging was being done for more consistency, to allow stream and file logs to run separately and turned on and off correctly , but also to move all the print statements over to the logs. logging.info() speaks to the general logging, but self.log.info() speaks to the one attached to the imexamine object you're using.  Let me know if you run into any other oddities!

**Comment by emcangi** [comment]
Ugh! I swear I read the documentation but I somehow missed that capability of set_plot_pars. XD

Thanks for helping, I know a lot of support for scientific programming packages is outside of normal job duties. Not sure if this is the case with you, but I do appreciate the amount of work that goes into OSS either way.
